#!/bin/zsh

function nv {
	SUDO="sudo"
	# SUDO="doas"

	FILEPATH=$1
	PARENT_DIR=$(dirname $FILEPATH)

	# Check if the parent directory exists and create it if not
	[[ -d $PARENT_DIR ]] || mkdir --parents $PARENT_DIR

	# Check if the file is writable and edit with SUDO if not
	if [ -w $FILEPATH ] || [ -w $PARENT_DIR ]
	then
		$EDITOR $FILEPATH
	else
		echo "$FILEPATH is a not writable"
		echo "Enter your $SUDO password\n"

		$SUDO $EDITOR $FILEPATH
	fi
}
