#!/usr/bin/env zsh


function pm {
  PROJECTS_DIR="$HOME/Documents/Projects/"

  case "$1" in
    o)
      PROJECT_PATH="$PROJECTS_DIR/$2"
      PROJECT_NAME="$2"
      ;;
    op)
      PROJECT_PATH="$2"
      PROJECT_NAME=$(basename "$2")
      ;;
    ot)
      PROJECT_PATH="/tmp/$USER-projects/$2"
      PROJECT_NAME="$2"
      ;;
    *)
      return ;;
  esac

  mkdir --parents "$PROJECT_PATH"
  pushd "$PROJECT_PATH"
  tmux new-session -s "$PROJECT_NAME"
  popd
}
