#!/bin/bash

SCRIPTPATH=$(cd -- $(dirname $0) > /dev/null 2>&1 ; pwd)

function link() {
	[ -e $2 ] && return

	mkdir --parents $(dirname $1)

	ln --symbolic $SCRIPTPATH/$1 $2
}

link zshrc ~/.config/zsh/.zshrc

link functions ~/.local/share/zfunctions

link alacritty ~/.config/alacritty

link neovim ~/.config/nvim
