#!/usr/bin/env bash

_safe_link () {
  if [ -e $2 ] ; then
    echo "Not linking '$2', as it already exists."
    return
  fi

  mkdir --parents $(dirname $1)
  ln --symbolic $(cd -- $(dirname $0) > /dev/null 2>&1 ; pwd)/$1 $2
}

_ensure_installed () {
  # TODO: implement other package manager support (ie. apt, dpkg, portage, ...)

  # determine all missing packages
  MISSING=$(pacman -Q $* 2>/dev/stdout 1>/dev/null | awk '{print $3}' | tr -d \')

  # install missing packages if there are any
  [ -z $MISSING ] || echo "paru -S $(echo $MISSING)"
}

_install() {
  PROGS=()

  for ARG in $@ ; do
    if [[ $ARG == 'zsh' || $ARG == 'all' ]] ; then
      PROGS+='zsh lsd starship pfetch-rs zsh-fast-syntax-highlighting zsh-vi-mode zoxide ripgrep fd '
    fi
    if [[ $ARG == 'kitty' || $ARG == 'all' ]] ; then
      PROGS+='kitty '
    fi
    if [[ $ARG == 'nvim' || $ARG == 'all' ]] ; then
      PROGS+='neovim '
    fi
    if [[ $ARG == 'hyprland' || $ARG == 'all' ]] ; then
      PROGS+='hyprland swww '
    fi
    if [[ $ARG == 'rofi' || $ARG == 'all' ]] ; then
      PROGS+='rofi-lbonn-wayland-git '
    fi
    if [[ $ARG == 'eww' || $ARG == 'all' ]] ; then
      PROGS+='eww '
    fi
    if [[ $ARG == 'tmux' || $ARG == 'all' ]] ; then
      PROGS+='tmux '
    fi
  done

  _ensure_installed $PROGS
}

_link() {
  # ensure that $XDG_CONFIG_HOME is set
  if [ -z $XDG_CONFIG_HOME ] ; then
    echo "'XDG_CONFIG_HOME' is not set." >&2
    echo "It should be set (likely to $HOME/.config) to link configs."
    return -1
  fi

  for ARG in $@ ; do
    if [[ $ARG == 'zsh' || $ARG == 'all' ]] ; then
      _safe_link zsh $XDG_CONFIG_HOME/zsh
    fi
    if [[ $ARG == 'kitty' || $ARG == 'all' ]] ; then
      _safe_link kitty $XDG_CONFIG_HOME/kitty
    fi
    if [[ $ARG == 'nvim' || $ARG == 'all' ]] ; then
      _safe_link nvim $XDG_CONFIG_HOME/nvim
    fi
    if [[ $ARG == 'hyprland' || $ARG == 'all' ]] ; then
      echo "source = ./presets/default.hl" > ./hypr/hyprland.conf
      _safe_link hypr $XDG_CONFIG_HOME/hypr
    fi
    if [[ $ARG == 'rofi' || $ARG == 'all' ]] ; then
      _safe_link rofi $XDG_CONFIG_HOME/rofi
    fi
    if [[ $ARG == 'eww' || $ARG == 'all' ]] ; then
      _safe_link eww $XDG_CONFIG_HOME/eww
    fi
    if [[ $ARG == 'tmux' || $ARG == 'all' ]] ; then
      _safe_link tmux $XDG_CONFIG_HOME/tmux
    fi
  done
}

_workspaces() {
  pushd ./dotfiles-rs/
  cargo build --bin workspace-rs --release
  popd
  
  _safe_link ./dotfiles-rs/target/release/workspace-rs ./scripts/workspace-rs
}

_select_preset() {
  sed --in-place "s|\(source = \./presets\).*|\1/$1\.hl|" ./hypr/hyprland.conf
}

case "$1" in
  install)
    _install $@ ;;
  link)
    _link $@ ;;
  workspaces)
    _workspaces ;;
  preset)
    _select_preset $2 ;;
  everything)
    ./setup install all
    ./setup link all
    ./setup workspaces
    ;;
  *)
    ;;
esac
