#!/bin/sh

_get_level() {
	cat /sys/class/power_supply/BAT0/capacity
}

_get_status() {
	cat /sys/class/power_supply/BAT0/status
}

[ $1 = "level" ] && _get_level && return
[ $1 = "status" ] && _get_status && return
