#!/bin/sh

. $(dirname $0)/listen

# Define which workspaces should be listened to
FROM=$1
TO=$2

# Looks like this line causes issues
# hyprctl monitors -j | jq --raw-output '.[0].activeWorkspace.id'

listen | while read -r line
do
  CURR=$(echo $line | awk -F '>>' -e '/^workspace>>/ {print $2}')

  [ -z $CURR ] && continue

  if [ $CURR -ge $FROM ] && [ $CURR -le $TO ]
  then
    echo $CURR
  fi
done
