#!/bin/sh

. $(dirname $0)/listen 

# Define which workspaces should be listened to
FROM=$1
TO=$2

workspaces() {
	WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')

	seq $FROM $TO | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

workspaces
listen | while read -r line
do
	workspaces 
done
