#!/bin/sh

_check_status() {
	DEV=$(ip link | awk '/state UP/ {print $2}' | tail -1)

	if ( ping -c 1 1.1.1.1 || ping -c 8.8.8.8 ) > /dev/null 2>&1
	then
		case $DEV in
			(e*)
				echo "Wired" ;;
			(w*)
				echo "Wireless" ;;
		esac
	else
		echo "Unavailable"
	fi
}

_signal_strength() {
		awk '{print $3}' /proc/net/wireless | tail -1 | tr -d .
	}

if [ "$1" = "status" ]
then
	_check_status
elif [ "$1" = "strength" ] 
then
	_signal_strength
fi
