#!/bin/sh

SUDO="sudo"
# SUDO="doas"

_start () {
	START_CMD="$SUDO systemctl start jellyfin-docker.service"

	if (mount | grep -q 'Koyori/MEDIA/*')
	then
		echo "Media drive is already mounted, starting Jellyfin..."
		$START_CMD
	elif ($SUDO mount -a)
	then
		echo "Mounted media drive, starting Jellyfin..."
		$START_CMD
	else
		echo "Media drive is not and can not be mounted"
		exit 1
	fi
}

_stop () {
	echo "Stopping Jellyfin..."
	$SUDO systemctl stop jellyfin-docker.service

	echo "Unmounting media drive..."
	$SUDO umount /srv/jellyfin/media/*
}

if [ "$1" = "start" ]
then
	_start
elif [ "$1" = "stop" ]
then
	_stop
else
	echo "Use 'start' or 'stop' subcommand"
	exit 1
fi

echo "Done"
