#!/bin/sh

update_eww() {
	PLAYER_STATUS=$(playerctl status)
	CURRENT_PLAYER=$(playerctl metadata | grep -m1 -oP '\K(firefox|spotify)' | head -1)

	eww ping > /dev/null 2>&1 && \
		eww update media-current-player="$CURRENT_PLAYER" ;
		eww update media-player-status="$PLAYER_STATUS" &
}

_get_cover() {
  URL=$(playerctl --player="$1" metadata | awk '/artUrl/ {print $3}')

  if ( echo $URL | grep -q "https" )
  then
    (cd /tmp && curl $URL -o downloaded_cover 2> /dev/null)
    echo "/tmp/downloaded_cover"
  else
    echo $URL | sed 's|file://||g'
  fi
}

_player() {
  if [ -z "$2" ]
  then
    (playerctl "$1" --player=spotify) || \
      (playerctl "$1" --player=firefox)
  elif [ "$2" = "all" ]
  then
		playerctl --all-players "$1"
  else
	  playerctl --player="$2" "$1"
  fi
}

[ "$1" = "play-pause" ] || \
	[ "$1" = "next" ] || \
	[ "$1" = "previous" ] && \
	_player "$1" "$2"

[ "$1" = "cover" ] && _get_cover $2
